"""Add name to Record table

Revision ID: 0d0d82c43440
Revises: 39e59ebcb30c
Create Date: 2018-07-04 17:31:53.329749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d82c43440'
down_revision = '39e59ebcb30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('name', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_column('record', 'name')
    # ### end Alembic commands ###
