"""BookRecord table

Revision ID: 9c9ba984f6cc
Revises: 0d0d82c43440
Create Date: 2018-07-05 10:18:54.238516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9ba984f6cc'
down_revision = '0d0d82c43440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('brn', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_record_name'), 'book_record', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_record_name'), table_name='book_record')
    op.drop_table('book_record')
    # ### end Alembic commands ###
